# Generated by Django 5.0.6 on 2024-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('hospital_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
