# Generated by Django 5.0.6 on 2024-06-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankers_app', '0002_hospitalform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalform',
            old_name='email',
            new_name='hospital_email',
        ),
        migrations.CreateModel(
            name='Donorprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('phonenumber', models.IntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bloodbankers_app.customuser')),
            ],
        ),
    ]
