# Generated by Django 5.0.6 on 2024-06-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankers_app', '0003_rename_email_hospitalform_hospital_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_name',
        ),
    ]
