# Generated by Django 5.0.6 on 2024-06-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankers_app', '0004_remove_donorprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFillingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_date_donating', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, max_length=3, null=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bloodbankers_app.donorprofile')),
            ],
        ),
    ]
