# Generated by Django 5.0.6 on 2024-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankers_app', '0005_donorfillingform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorprofile',
            old_name='phonenumber',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='Last_date_donating',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='bloodgroup',
            field=models.CharField(blank=True, default='UNK', max_length=3),
        ),
        migrations.DeleteModel(
            name='DonorFillingForm',
        ),
    ]
